services:
  - type: web
    name: ttc-app
    env: node
    buildCommand: pnpm install && pnpm build
    startCommand: cd packages/server && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
