services:
  - type: web
    name: ttc-app
    env: node
    buildCommand: pnpm install && pnpm build && cd packages/server && pnpm run postbuild
    startCommand: cd packages/server && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://ttc-db_owner:npg_c9G8zoIqnPEd@ep-small-flower-a863t5i1-pooler.eastus2.azure.neon.tech/ttc-db?sslmode=require
