name: Deploy Server

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        cd packages/server
        npm install
        
    - name: Build
      run: |
        cd packages/server
        npm run build
        
    # Example deployment to Railway
    # Uncomment and configure as needed
    # - name: Deploy to Railway
    #   run: |
    #     npm install -g @railway/cli
    #     cd packages/server
    #     railway up
    #   env:
    #     RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
